### ISSUE TITLE
Adjust Calculations and add library for formatting

### ISSUE THREAD

**Issue by Sjefkesuit** [cre-project/pdf-app#15]
Make sure that nothing shows up as Nan or Infinity 

Add accounting JS so we can format money

**Comment by m-ke** [comment]
I added another check to preview page to disallow showing the preview if no OS data is present so NaN & Infinity shouldn't show up again.

Added filter in https://github.com/cre-project/pdf-app/commit/5364fe65e58d5fd2720f39f83530e969e7b70fd5

**Comment by m-ke** [comment]
ok, nvm, the check is not right
