### ISSUE TITLE
Saving images from pdf app

### ISSUE THREAD

**Issue by m-ke** [cre-project/pdf-app#9]
- [x] images that users upload are saved on cloudinary
- [x] once they're uploaded to cloudinary the resulting URL gets sent to the backend & saved in DB for the package
   -  [x] create backend API endpoint / update current one(s) to allow for this
- [x] update backend to save package images the same way as the other background images 
- [x] replace default images in the pdf by the actual images the user uploaded (use URLs saved in the package)
   - use image name selectors to get the div & change background img
- [x] make sure that the images set by users are set in both the preview and exported pdf (currently the url is saved in CSS & the preview uses a different css file from exported pdf)
- [x] make sure the images are displayed on pages where users uploaded them

**Comment by marionschleifer** [comment]
@m-ke It should now be possible to update image_urls.

Authentication is with the `PDF_APP_API_KEY`

This is the endpoint: 
`http://localhost:3000/api/packages/:package_id/update_images`

Pass the image urls in the body like this:
`{ "package": { "image_urls": ["234", "123"] }}`

Let me know if something is not working.

**Comment by m-ke** [comment]
we need to figure out how we link the images to the pages - we'll need to be able to get the image urls and put each in the correct page in the pdf  (ie replace the default ones) lmk if you have some ideas

**Comment by marionschleifer** [comment]
@m-ke I added the endpoints now. Sorry that the commit is not linked to this issue, I didn't have access on the flight. You find it here: https://github.com/cre-project/cre-backend/commit/fa6ca273b118473e4120b9309c68aa7635a672de

The `images_urls` (the four pictures on one section) stays the same as described above. Let me know if something doesn't work as planned, and I'll change it.

**Comment by m-ke** [comment]
Hey @marionschleifer 
I have troubles saving images...

```
 Started PUT "/api/packages/f63b2149-feb1-445c-8121-5f4fe2598df2/update_images" for 127.0.0.1 at 2019-02-02 20:49:24 +0100
Processing by Api::PackagesController#update_images as HTML
  Parameters: {"package"=>{"rent_comparables_cover_image_url"=>"https://res.cloudinary.com/dxnzksg0a/image/upload/v1549136963/pmh1ulpzixgarevhfpkp.png"}, "id"=>"f63b2149-feb1-445c-8121-5f4fe2598df2"}
  Package Load (0.4ms)  SELECT  "packages".* FROM "packages" WHERE "packages"."id" = $1 LIMIT $2  [["id", "f63b2149-feb1-445c-8121-5f4fe2598df2"], ["LIMIT", 1]]
  ↳ app/controllers/api/packages_controller.rb:112
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.4ms)


  
NoMethodError (undefined method `each' for nil:NilClass):
  
app/controllers/api/packages_controller.rb:92:in `update_images'

```
Is this from readme true? Is it why it's not working? ```Update images: PUT api/packages/:id/update_images (required: image_urls) ```

**Comment by m-ke** [comment]
ok, tested with different values. I'll try to fix the backend so that image_urls are not required.

**Comment by m-ke** [comment]
unfortunately the other image URLs don't get saved, only the image_urls :( 

```
Expanded display is on.
backend_development=# select * from packages where id = 'f63b2149-feb1-445c-8121-5f4fe2598df2';
-[ RECORD 1 ]------------------------+-------------------------------------
id                                   | f63b2149-feb1-445c-8121-5f4fe2598df2
template                             | default
created_at                           | 2019-01-19 19:10:45.887126
updated_at                           | 2019-02-02 19:57:49.768232
user_id                              | 742b3d1e-9404-474c-b451-c582e09e10c6
image_urls                           | {test}
cover_image_url                      | 
information_image_url                | 
table_of_contents_image_url          | 
property_information_cover_image_url | 
property_information_image_url       | 
property_photos_cover_image_url      | 
recent_sales_cover_image_url         | 
rent_comparables_cover_image_url     | 
pricing_cover_image_url              | 
closing_cover_image_url              | 
```

**Comment by m-ke** [comment]
Hey Marion, unfortunately saving images other than the array doesn't work. there's no permission to call package update & the new API method only saves the array. could you please update it so that the new api endpoint doesn't require image_urls and saves all fields that come? or if it's easier change the package update so that it can be called from the pdf app
